### ISSUE TITLE
How get name of contact from new message?

### ISSUE THREAD

**Issue by ilyaborodin** [adiwajshing/Baileys#92] opened 2020-08-02 19:30 UTC
Good day. If we look at the contacts that we received during logging, we will see that they have a notify field. This field stores the name of the whatsapp account. How can I get the name from a new message. Maybe there are methods with which I can get a contact object by whatsapp id? Or any other options? This field is very important to me. I would be glad to hear any suggestions. Thanks!!

**Comment by adiwajshing** [comment] 2020-08-03 05:05
I'm not sure actually -- but I am looking into it. However, this is a duplicate of #66

**Closed by adiwajshing** 2020-08-03 05:05 UTC
