### ISSUE TITLE
[BUG] o

### ISSUE THREAD

**Issue by OyenDCraft** [adiwajshing/Baileys#1032] opened 2021-12-16 03:38 UTC
O

**Comment by zennn08** [comment] 2021-12-16 03:48
but what i see is 400 bad requests 😂, so the problem is in your code, not in baileys

**Comment by zennn08** [comment] 2021-12-16 03:51
> 

lol
why did you edit your comment 😂

**Comment by OyenDCraft** [comment] 2021-12-16 03:52
> > 
> 
> lol why did you edit your comment 😂

O

**Comment by zennn08** [comment] 2021-12-16 03:53
> > > 
> > 
> > 
> > lol why did you edit your comment 😂
> 
> O

please close this issue

**Closed** 2021-12-16 04:07 UTC
Labels: bug
