### ISSUE TITLE
how to get number group online member

### ISSUE THREAD

**Issue by ianmsfvenom** [adiwajshing/Baileys#347] opened 2021-02-02 14:52 UTC
i use `await client.updatePresence(from, Presence.available)` but do not return the member online in the group, someone can help?

**Comment by Nurutomo** [comment] 2021-02-03 15:12
**How do i get someone last seen?

**Comment by adiwajshing** [comment] 2021-02-06 18:24
Duplicate of #314

**Closed by adiwajshing** 2021-02-06 18:24 UTC
