### ISSUE TITLE
Baileys & WhatsApp BETA

### ISSUE THREAD

**Issue by sasu08** [adiwajshing/Baileys#706] opened 2021-09-28 00:36 UTC
Hi! How's everybody? As you know, recently, WhatsApp launched a beta version where we can have up to 4 sessions at the same time.
Baileys is working really good with the stable version, but if I "upgrade" to beta version, my code throws an error:

> Error inesperado: TypeError: Cannot read property 'toString' of undefined
> (node:13068) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "key" argum
> ent must be of type string or an instance of Buffer, TypedArray, DataView, or KeyObject. Received undefined
>     at prepareSecretKey (internal/crypto/keys.js:322:11)
>     at Cipheriv.createCipherWithIV (internal/crypto/cipher.js:119:9)
>     at new Cipheriv (internal/crypto/cipher.js:227:22)
>     at Object.createCipheriv (crypto.js:124:10)
>     at Object.aesEncrypt (C:\Users\juanc\Desktop\sasu-whatsapp\node_modules\@adiwajshing\baileys
> \lib\WAConnection\Utils.js:107:24)
>     at WAConnection.sendBinary (C:\Users\juanc\Desktop\sasu-whatsapp\node_modules\@adiwajshing\b
> aileys\lib\WAConnection\0.Base.js:321:26)
>     at WAConnection.<anonymous> (C:\Users\juanc\Desktop\sasu-whatsapp\node_modules\@adiwajshing\
> baileys\lib\WAConnection\4.Events.js:86:18)
>     at WAConnection.emit (events.js:412:35)
>     at WAConnection.emit (C:\Users\juanc\Desktop\sasu-whatsapp\node_modules\@adiwajshing\baileys
> \lib\WAConnection\4.Events.js:668:41)
>     at WAConnection.connect (C:\Users\juanc\Desktop\sasu-whatsapp\node_modules\@adiwajshing\bail
> eys\lib\WAConnection\3.Connect.js:70:14)
> (Use `node --trace-warnings ...` to show where the warning was created)
> (node:13068) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
> (node:13068) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Okay, the problem is the data type received, but how can I solve that? or is Baileys not compatible yet?
Thank you!

**Comment by nekiak** [comment] 2021-09-28 07:14
Duplicate of #605

**Comment by frmdeveloper** [comment] 2021-09-29 15:29
Close !!

**Comment by sasu08** [comment] 2021-09-29 18:50
Thank you!

**Closed** 2021-09-29 18:50 UTC
