### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by OdinTm** [adiwajshing/Baileys#1628] opened 2022-05-16 17:30 UTC
"msg":"sent retry receipt"

**Comment by DentaCH** [comment] 2022-05-16 17:37
?????

**Comment by burstfreeze** [comment] 2022-05-16 17:45
That's not a bug. Some messages have to be retried.

**Comment by AkirahX** [comment] 2022-05-16 18:05
This is not a bug, if you don't want to get this warning just change the level your logger is at.

Close this guy.

**Closed** 2022-05-16 22:29 UTC
Labels: bug
