### ISSUE TITLE
Sending media / Files

### ISSUE THREAD

**Issue by mrbarnk** [adiwajshing/Baileys#3] opened 2020-04-01 23:00 UTC
How about sending files and medias? I haven't seen that function there.

If you need anyhelp, I'm willing to render.😉

**Comment by adiwajshing** [comment] 2020-04-02 07:13
So, this is a duplicate of this issue here: #2 

However, I haven't implemented sending media. However, please feel free to contribute! Do open a pull request for the same.

If you're interested in implementing sending files, I was thinking about an API like this:
``` javascript
const mediaBlob = fs.readFileSync("path/to/some/image.png") // load image blob
client.sendMediaMessage (personID, mediaBlob, WhatsAppWeb.Media.Image)
```
sendMediaMessage could be implemented in WhatsAppWeb.Send.js

Also, you could define Media enum as:
``` javascript
WhatsAppWeb.Media = {
    Image: 0,
    Video: 1,
    PDF: 2,
    ...    
}
```

**Closed by adiwajshing** 2020-04-02 07:13 UTC

**Comment by mrbarnk** [comment] 2020-04-02 09:29
How about converting files to data url, and sending that?

**Comment by adiwajshing** [comment] 2020-04-02 11:31
Sure, can add that too
