### ISSUE TITLE
[BUG] connect attempt 1 failed, retrying...

### ISSUE THREAD

**Issue by Hungry-Coder-byte** [adiwajshing/Baileys#532] opened 2021-06-16 08:07 UTC
**Getting error since today morning**

Till yesterday the code was working fine but today when I connected my system with internet, I started getting the error (or warning) -

connected to WhatsApp Web server, authenticating via takeover
connected to WhatsApp Web server, authenticating via takeover (**I have deleted my old session then why this warning prompt ?**)
connect attempt 1 failed, retrying...

Interesting thing is that, QR code is generated and then I get - 

WARN [2021-06-16 08:03:53.539 +0000] (4852): **connect attempt 3 failed, retrying...**
    class: "Baileys"
    error: {}

**Comment by JuanDelValle18** [comment] 2021-06-16 08:33
I also present the same problem, will there be something to fix it?

**Comment by Hungry-Coder-byte** [comment] 2021-06-16 08:36
> I also present the same problem, will there be something to fix it?

I tried -

1. Deleting my old session
2. Update the packages (npm update)
3. Restarted the system

In one of my system it fixed the issue, but in another system I am still getting the same error.

**Comment by JuanDelValle18** [comment] 2021-06-16 08:50
> > También presento el mismo problema, ¿habrá algo para solucionarlo?
> 
> Lo intenté -
> 
> 1. Eliminando mi antigua sesión
> 2. Actualizar los paquetes (actualización npm)
> 3. Reinicia el sistema
> 
> En uno de mis sistemas se solucionó el problema, pero en otro sistema sigo recibiendo el mismo error.


Could you tell me what commands you executed?

**Comment by Hungry-Coder-byte** [comment] 2021-06-16 08:53
> > > También presento el mismo problema, ¿habrá algo para solucionarlo?
> > 
> > 
> > Lo intenté -
> > 
> > 1. Eliminando mi antigua sesión
> > 2. Actualizar los paquetes (actualización npm)
> > 3. Reinicia el sistema
> > 
> > En uno de mis sistemas se solucionó el problema, pero en otro sistema sigo recibiendo el mismo error.
> 
> Could you tell me what commands you executed?

I just deleted the file which contains the session - **rm <session_filename>.json**
and then, **npm update** to update the packages inside my application folder
and then, restarted the system and started my app

**Comment by SheIITear** [comment] 2021-06-16 09:02
Duplicate of #526. Please check other issues before making new ones.

**Closed** 2021-06-16 09:08 UTC
Labels: bug
