### ISSUE TITLE
[ Multi Device ] messages.upsert event stops working after a few minutes connected

### ISSUE THREAD

**Issue by frmontini** [adiwajshing/Baileys#751] opened 2021-10-19 22:13 UTC
**Describe the issue**
A few minutes after read the QR Code, the `messages.upsert` event stops working.

**To Reproduce**

1. Put a console.log on `messages.upsert` event
2. Create a new connection
3. Wait for a few minutes

**Expected behavior**
I expect to receive all new messages on `messages.upsert` event without interruption

**Environment (please complete the following information):**

- Running on localhost
- Options to start a connection: { logger: P({ level: 'silent' }), browser: ['MyAppName', 'Google Chrome', '18.04'] }
- Only my WhatsApp number on my localhost
- I'm not using a proxy

**Comment by burstfreeze** [comment] 2021-11-07 10:03
Can you check whether during this happening you still can SEND messages that appear on other devices as well as in the .upsert event? I am asking because it does literally that for me.

Receiving is not possible anymore but sending works and my sent messages also cause an upsert just like they would normally

**Comment by LuanRT** [comment] 2021-11-07 10:13
> Can you check whether during this happening you still can SEND messages that appear on other devices as well as in the .upsert event? I am asking because it does literally that for me.
> 
> Receiving is not possible anymore but sending works and my sent messages also cause an upsert just like they would normally

Same, whenever this happens it is still able to send messages normally.

**Comment by burstfreeze** [comment] 2021-11-07 10:15
> Same, whenever this happens it is still able to send messages normally.

Do they also appear in the upsert for you?

**Comment by LuanRT** [comment] 2021-11-07 10:18
> > Same, whenever this happens it is still able to send messages normally.
> 
> Do they also appear in the upsert for you?

Yup.

**Comment by burstfreeze** [comment] 2021-11-07 11:49
I now have a session where it fails silently, with the #744

**Comment by burstfreeze** [comment] 2021-11-07 11:49
I now have a session where it fails silently, without the failure message in #744

**Comment by burstfreeze** [comment] 2021-11-07 12:38
There is something I noticed. We should at least see server events coming in. In my case, there aren't even any incoming messages except for ongoing pings.

**Comment by LuanRT** [comment] 2021-11-07 18:10
> There is something I noticed. We should at least see server events coming in. In my case, there aren't even any incoming messages except for ongoing pings.
> 
> Also no typing messages etc.

And btw I forgot to mention something—
The session starts working normally after a few hours (or even a day), I don't know if you ever waited that much to test it but it already happened multiple times here and I can confirm that the session would always “recover” itself somehow, all events start working again.

**Comment by adiwajshing** [comment] 2021-11-07 18:26
Interesting, I've noticed the same. Not sure right now as to why it happens

**Comment by burstfreeze** [comment] 2021-11-07 18:33
> And btw I forgot to mention something— The session starts working normally after a few hours (or even a day), I don't know if you ever waited that much to test it but it already happened multiple times here and I can confirm that the session would always “recover” itself somehow, and all events start working again.

I can confirm that for one instance but I don't know if the root of the issue was the same as with the other ones.

**Comment by burstfreeze** [comment] 2021-11-07 18:36
> Interesting, I've noticed the same. Not sure right now as to why it happens

This is the best message I could've wished for. I am happy you can reproduce the issue since you are basically the top authority on it.

One thing that came to my mind: In legacy, if you do not send a presence available within about 30 seconds after connecting, you would still receive ping pongs but no content. This is a very similar situation here, except that I've verified that you already send presence. Baileys legacy also sent status polls when connecting - could the WA backend expect something along the lines of that? What brings me OFF this course is that often it works and other times it breaks which speaks against the presence/ status poll thesis.

**Comment by LuanRT** [comment] 2021-11-07 18:45
> > And btw I forgot to mention something— The session starts working normally after a few hours (or even a day), I don't know if you ever waited that much to test it but it already happened multiple times here and I can confirm that the session would always “recover” itself somehow, and all events start working again.
> 
> I can confirm that for one instance but I don't know if the root of the issue was the same as with the other ones.

In my case it happened with pretty much all sessions that would face this exact problem. Might be due to the server expecting something.
I think this is the only major problem now.

**Comment by adiwajshing** [comment] 2021-11-08 09:34
I believe I found the source, if ya'll can confirm:

this issue occurs when you try to open the same session in multiple times simultaneously -- causing a bunch of conflict stream:errors.

**Comment by burstfreeze** [comment] 2021-11-08 12:36
> I believe I found the source, if ya'll can confirm:
> 
> this issue occurs when you try to open the same session in multiple times simultaneously -- causing a bunch of conflict stream:errors.

@adiwajshing Do you mean having multiple Baileys sessions using the same auth file? If so, that's not the cause for me :/

**Comment by adiwajshing** [comment] 2021-11-08 13:40
I mean using the same credentials to open a session in multiple places at the same time

**Comment by burstfreeze** [comment] 2021-11-08 14:02
If by "credentials" you mean the json, what do you mean by "multiple places"?

**Comment by frmontini** [comment] 2021-11-08 16:02
@adiwajshing for me this issue happens without any logic. to solve for now, i'm using the socket.end() after a few minutes without send messages and calling makeWASocket to restart a connection with saved credentials and works fine. I'm online since last friday, sending and receiving new messages.

**Comment by canove** [comment] 2021-11-08 16:22
Same here. My context is:

The session was working fine, reconnecting every 50 minutes due to https://github.com/adiwajshing/Baileys/issues/810, but no problems for the past 5 days.

After the last connection, it stopped receiving messages. 

Sending messages keep working.

I could not bring it back, even restarting the server didn't make it work. I had to logout and scan QR code again to start receiving messages.

**Comment by burstfreeze** [comment] 2021-11-10 18:32
At the moment I am only seeing rare #744 issues, they do come up **but most of the time it fails silently.**

Sometimes it starts to load a few chats again but most of the time I simply see nothing - at this point I am a strong supporter of the soft logout theory that @pokearaujo came up with.

**Comment by adiwajshing** [comment] 2021-11-10 18:40
This issue should be resolved in https://github.com/adiwajshing/Baileys/pull/696/commits/cfa7e8ec66aab05baa30aeb1e167d149528f9f52

Ya'll will have to login again tho for the change to take effect. Feel free to open if not resolved

**Closed by adiwajshing** 2021-11-10 18:40 UTC
Labels: bug
