### ISSUE TITLE
Is it possible to track a random phone number?

### ISSUE THREAD

**Issue by ahmtxonly** [adiwajshing/Baileys#108] opened 2020-08-14 23:21 UTC
Is it possible to track a random phone number?
To follow a number that is not in our directory

**Comment by adiwajshing** [comment] 2020-08-15 08:11
More often than not, no. However, it can be done for some numbers based on their privacy settings.

As this is a duplicate of #79, I'm closing the issue.

**Closed by adiwajshing** 2020-08-15 08:11 UTC
