### ISSUE TITLE
Live localization

### ISSUE THREAD

**Issue by algoz098** [adiwajshing/Baileys#158] opened 2020-09-17 02:06 UTC
Would be nice to be able to send and update a live localization.

I tried to see if i could implement in by myself, but the flow of data if a binary of a octa-stream. Maybe i can help, but i do not understand too much

**Comment by adiwajshing** [comment] 2020-09-18 10:50
You mean `live locations`?

**Comment by algoz098** [comment] 2020-09-18 12:26
yes

**Comment by adiwajshing** [comment] 2020-09-18 13:31
Duplicate of #140. Closing.

**Closed by adiwajshing** 2020-09-18 13:31 UTC
