### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Millena543** [adiwajshing/Baileys#814] opened 2021-11-09 02:26 UTC
I'm having trouble adding the bot to new groups, it just doesn't respond.  

WARN [2021-11-07 14:32:55.910 +0000] (4150): recieved odd group ID gid: "120363039905510325@g.us" class: "Baileys"

**Comment by Millena543** [comment] 2021-11-09 02:28
WARN [2021-11-07 14:32:55.910 +0000] (4150): recieved odd group ID gid: "120363039905510325@g.us" class: "Baileys"

**Comment by azudindaem** [comment] 2021-11-09 03:17
Duplicate of #805

**Closed** 2021-11-09 10:41 UTC
Labels: bug
