### ISSUE TITLE
WARN [2021-06-16 05:59:45.915 +0000] (3776): connect attempt 6 failed: Error: close, retrying...     class: "Baileys"     error: {}

### ISSUE THREAD

**Issue by MAlifJian** [adiwajshing/Baileys#531] opened 2021-06-16 06:04 UTC
Now I got this , I just copy example code but show error like this 

async function start (){
    const alf = new WAConnection();
    alf.connect();
    alf.on('chat-update', (cht) => {
        console.log(cht.jid);
    }
)}
start().catch (err => console.log("unexpected error: " + err) )

**Comment by SheIITear** [comment] 2021-06-16 06:07
Duplicate of #526. Please check other issues before making new ones.

**Comment by MAlifJian** [comment] 2021-06-16 06:12
How fix that?
Sorry i new in github

Pada tanggal Rab, 16 Jun 2021 13.07, ShellTear ***@***.***>
menulis:

**Closed** 2021-06-16 06:19 UTC
