### ISSUE TITLE
AUDIO SEND INVALID (0:00 SECONDS)

### ISSUE THREAD

**Issue by danielteodorodt** [adiwajshing/Baileys#197] opened 2020-10-20 18:06 UTC
Hello, I thank you in advance for this well structured project with many events that we can use.

Anyway, when you are going to send an audio, either by voice, or file is going to reset the seconds.

It only plays on WhatsApp Web.

```javascript
let buffer = fs.readFileSync('./audio.ogg')
const options = { mimetype: Mimetype.ogg, ptt: true }
conn.sendMessage(m.key.remoteJid, buffer, MessageType.audio, options)
```

![image](https://user-images.githubusercontent.com/64978981/96626378-cfea9480-12e5-11eb-9a8c-d94430232e02.png)

**Comment by itacirgabral** [comment] 2020-10-21 13:07
Are you recording this audio from chrome? It's have a bug and can't record on opus container.

I'm using this https://github.com/chris-rudmin/opus-recorder
![Screenshot from 2020-10-21 09-04-04](https://user-images.githubusercontent.com/6052177/96723483-9c0e7e00-137c-11eb-9e61-6579021356c3.png)

**Comment by danielteodorodt** [comment] 2020-10-21 13:35
> Você está gravando este áudio do Chrome? Ele tem um bug e não pode gravar no container Opus.
> 
> Estou usando este https://github.com/chris-rudmin/opus-recorder
> ![Captura de tela de 2020-10-21 09-04-04](https://user-images.githubusercontent.com/6052177/96723483-9c0e7e00-137c-11eb-9e61-6579021356c3.png)

**Comment by danielteodorodt** [comment] 2020-10-21 13:37
> Are you recording this audio from chrome? It's have a bug and can't record on opus container.
> 
> I'm using this https://github.com/chris-rudmin/opus-recorder
> ![Screenshot from 2020-10-21 09-04-04](https://user-images.githubusercontent.com/6052177/96723483-9c0e7e00-137c-11eb-9e61-6579021356c3.png)

No, I take an MP3 audio, convert it to OGG with ffmeg, and try to send it. I don't record. It is an audio ready.

**Comment by danielteodorodt** [comment] 2020-10-21 13:37
@itacirgabral  No, I take an MP3 audio, convert it to OGG with ffmeg, and try to send it. I don't record. It is an audio ready.

**Comment by eabuslaiman** [comment] 2020-10-21 14:31
@danielteodorodt Duplicated of #189.

**Comment by danielteodorodt** [comment] 2020-10-21 14:42
@eabuslaiman  Yours has not been resolved, so open mine.

**Comment by adiwajshing** [comment] 2020-10-22 16:43
@danielteodorodt this is a duplicate of #189, which has only just been resolved with the latest commit. Closing this.

**Closed** 2020-10-22 16:43 UTC
