### ISSUE TITLE
[ERROR]

### ISSUE THREAD

**Issue by tahaluindo** [adiwajshing/Baileys#1779] opened 2022-06-22 14:38 UTC
why bro?

![Screenshot_2022-06-22-21-37-22-41](https://user-images.githubusercontent.com/94370774/175056895-83989cf4-00df-4671-8ec5-27925de63aa2.png)

**Comment by phaticusthiccy** [comment] 2022-06-22 17:13
We can't make any comments without seeing the code. I've never encountered TypeErors into baileys previously. This error is most likely caused by your code. Please check the line at the error address.

**Comment by adiwajshing** [comment] 2022-06-23 05:46
Closing for an absolute disregard for the issue template, and for not doing their own due diligence

**Closed by adiwajshing** 2022-06-23 05:46 UTC
Labels: bug

**Comment by tahaluindo** [comment] 2022-06-24 21:07
ok
